 version: 2
 jobs:
   build:
     docker:
       - image: circleci/golang:1.13
     steps:
       - checkout
       - run: git rev-parse HEAD
       - run:
          command: | 
            export GOPATH=~/project
            export GOBIN=~/project
            export PATH=$PATH:$GOROOT/bin:$GOPATH:$GOBIN
            mkdir src
            go version
            go env
            echo $GOPATH
            go get
            docker build -t go-docker .
            docker images
            docker ps
       - run: ls
       - run: go version
       - run: go env
       - run: echo $gopath
       - run: pwd
       - run: go get
       - run: docker build -t go-docker
       - run: docker images
