 version: 2
 jobs:
   build:
     docker:
       - image: circleci/golang:1.8.6-jessie
     steps:
       - checkout
       - run: | 
            "echo 'lastcommitsha: ' >> metadata"
            git rev-parse HEAD >> metadata
            cat metadata
       - run:
          command: | 
            export GOPATH=~/project
            export GOBIN=~/project
            export PATH=$PATH:$GOROOT/bin:$GOPATH:$GOBIN
            mkdir src
            go get

       - setup_remote_docker:
          docker_layer_caching: false
        
       - run:
          name: Install Docker Client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin --force
       - run: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t go-docker-api:$TAG .
            docker version
            docker images
            docker ps
