 version: 2
 jobs:
   build:
     docker:
       - image: circleci/golang:1.13
     steps:
       - checkout
       - run:
          command: | 
            export GOPATH=~/project
            export GOBIN=~/project
            export PATH=$PATH:$GOROOT/bin:$GOPATH:$GOBIN
            go env -w GOPATH=~/project
            pwd
            ls
            mkdir src
            ls
            go version
            go env
            echo $GOPATH
       - run: pwd
       - run: go get
       - run: docker build -t go-docker
       - run: docker images
