 version: 2
 jobs:
   build:
     docker:
       - image: circleci/golang:1.12
     steps:
       - checkout
       - run: echo "A first hello"
       - run: git rev-parse HEAD
       - run: go get
       - run: docker build -t go-docker
