 version: 2
 jobs:
   build:
     docker:
       - image: circleci/golang:1.12
     working_directory: ~/usr/local
     steps:
       - run: cd "~/usr/local/go"
       - checkout
       - run: echo "A first hello"
       - run: git rev-parse HEAD
       - run: ls
       - run: go version
       - run: go env
       - run: echo $gopath
       - run: pwd
       - run: mkdir src
       - run: go get
       - run: docker build -t go-docker
       - run: docker images
