 version: 2
 jobs:
   build:
     docker:
       - image: circleci/golang:1.13
     steps:
       - checkout
       - run: git rev-parse HEAD
       - run:
          command: | 
            export GOPATH=~/project
            export GOBIN=~/project
            export PATH=$PATH:$GOROOT/bin:$GOPATH:$GOBIN
            mkdir src
            go version
            go env
            echo $GOPATH
            go get

            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            apt-key fingerprint 0EBFCD88
            add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce
            docker version

            sudo docker build -t go-docker .
            sudo docker images
            sudo docker ps
       - run: ls
       - run: go version
       - run: go env
       - run: echo $gopath
       - run: pwd
       - run: go get
       - run: docker build -t go-docker
       - run: docker images
