 version: 2
 jobs:
   build:
     docker:
       - image: circleci/golang:1.8.6-jessie
     steps:
       - checkout
       - run: 
          name: Getting the last commit sha and modifying the metadata file
          command: | 
            sha=`git rev-parse HEAD`
            sed -i "s/<replace>/$sha/g" metadata
            cat metadata
       - run:
          name: Setting up golang environment and building go application to test locally
          command: | 
            export GOPATH=~/project
            export GOBIN=~/project
            export PATH=$PATH:$GOROOT/bin:$GOPATH:$GOBIN
            mkdir src
            go get
            go build -o main .
            #unit test don't seem to work
            #go test -v
            ls
            ./main &
            # curling the points for maunal test -- however in future would like it to be more automatic
            curl http://localhost:8080
            curl http://localhost:8080/status
       - setup_remote_docker:
          docker_layer_caching: false
        
       - run:
          name: Install Docker Client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin --force
       - run: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t go-docker-api:latest .
            docker version
            docker images
            docker ps

       - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"
            docker push go-docker-api:latest