 version: 2
 jobs:
   build:
     docker:
       - image: circleci/golang:1.8.6-jessie
     steps:
       - checkout
       - run: | 
            sha=`git rev-parse HEAD`
            sed -i "s/<replace>/$sha/g" metadata
            cat metadata
       - run:
          command: | 
            export GOPATH=~/project
            export GOBIN=~/project
            export PATH=$PATH:$GOROOT/bin:$GOPATH:$GOBIN
            mkdir src
            go get
            go build -o main .
            ls
            ./main &
            curl http://localhost:8080
            curl http://localhost:8080/status
       - setup_remote_docker:
          docker_layer_caching: false
        
       - run:
          name: Install Docker Client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin --force
       - run: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t go-docker-api .
            docker version
            docker images
            docker ps

       - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker run -d -p 8080:8080 --name go-docker-api-c go-docker-api
            docker ps
            curl --retry 10 http://localhost:8080
            curl --retry 10 http://localhost:8080/status
            #docker exec go-docker-api-c curl --retry 10 --retry-connrefused http://localhost:8080
            #docker exec go-docker-api-c curl --retry 10 --retry-connrefused http://localhost:8080/status
